#!/usr/bin/env bash
curl 'https://public-api.wordpress.com/rest/v1.1/sites/quiteaquote.in/posts/?pretty=true&context=display&page=2&number=1&fields=title,content&category=thought%20for%20today&type=post&status=publish&post_ID=0'
curl 'https://public-api.wordpress.com/rest/v1.1/sites/quiteaquote.in/posts/?pretty=true&context=display&page=2&number=1&fields=title,content,ID&category=thought%20for%20today&type=post&status=publish&ID=0'
