#!/usr/bin/env bash
require() {
  hash "$@" | exit
}
require curl jq shuf
count=$(curl --silent 'https://public-api.wordpress.com/rest/v1.1/sites/quiteaquote.in/posts/?pretty=true&context=display&page=1&number=1&fields=found&category=thought%20for%20today&type=post&status=publish' | jq '.found')
# Generate a random number using shuf
rnd="$(shuf -i 1-"${count}" -n 1)"
curl --silent "https://public-api.wordpress.com/rest/v1.1/sites/quiteaquote.in/posts/?pretty=true&context=display&page=${rnd}&number=1&fields=title,content,ID,short_URL,URL&category=thought%20for%20today&type=post&status=publish&ID=0" |
  jq ".posts[0] | .title,.content,.short_URL,.URL"
cnt="$(curl --silent "https://public-api.wordpress.com/rest/v1.1/sites/quiteaquote.in/posts/?pretty=true&context=display&page=1&number=1&fields=found,title,content,ID,short_URL,URL&category=thought%20for%20today&type=post&status=publish&ID=0&after=20120101&before=20120131" |
  jq ".found")"
curl --silent "https://public-api.wordpress.com/rest/v1.1/sites/quiteaquote.in/posts/?context=display&page=1&number=1&fields=found,title,content,ID,short_URL,URL&category=thought%20for%20today&type=post&status=publish&ID=0&after=20120101&before=20120131&order=ASC&order_by=date" |
  jq ".posts[0] | .title,.content,.short_URL,.URL"
curl --silent "https://public-api.wordpress.com/rest/v1.1/sites/quiteaquote.in/posts/?context=display&page=${cnt}&number=1&fields=found,title,content,ID,short_URL,URL&category=thought%20for%20today&type=post&status=publish&ID=0&after=20120101&before=20120131&order=ASC&order_by=date" |
  jq ".posts[0] | .title,.content,.short_URL,.URL"
