var x:number = 20 
var y:number = 2 
var result:number = 0
result = x + y; 
console.log("20 + 2 = " + result);  
result = x / y; 
console.log("20 / 2 = " + result); 
result = x % y; 
console.log("20 % 2 = " + result); 
result = ++x; 
console.log("++x = " + result); 
