#!/usr/bin/env bash
filename="$1"
filename="${filename%.*}"
if [[ -e "$filename".js ]]
then
  rm "$filename".js
fi
tsc -t es2015 --pretty "$1"
ret="$?"
if [[ 0 -eq "$ret" ]]
then
  node "$filename".js
fi
exit "$ret"
