#!/usr/bin/env bash
filename="$1"
filename="${filename%.*}"
if [[ -e "$filename".js ]]; then
  rm "$filename".js
fi
tsc "$(strip-json-comments tsconfig.json | jq -r '.compilerOptions | to_entries[] | "--\(.key) \(.value)"') --pretty ${1}"
#tsc -t es2015 --pretty "$1"
ret="$?"
if [[ 0 -eq "$ret" ]]; then
  node "$filename".js
fi
exit "$ret"
